language: php

env:
  global:
    - XDEBUG_MODE=coverage

php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
  - php code-coverage.php clover.xml 80